-- Startgegevens voor de Thailand-reisapp
begin;

insert into bases (id,nr,name,dates,nights,lat,lon,hotel,alternative,why,todo,unsplash_query,maps_query,photo,photo_caption,gallery,links) values ('bkk',1,'Bangkok','3–5 feb','2 nachten',13.745,100.491,'ARUN Riverside','Sala Rattanakosin','Balkons met uitzicht op Wat Arun, op loopafstand van Wat Pho. Geen lift.',array['Wat Pho en de expressboot over de Chao Phraya','Fietstour door Bang Krachao','Muay Thai in Rajadamnern en een rooftopbar','Jodd Fairs-nachtmarkt']::text[],'wat-arun','ARUN Riverside Bangkok','01-wat-arun','Wat Arun aan de Chao Phraya','[["02-wat-arun-avond", "Wat Arun bij zonsondergang"], ["03-bangkok-fietsen", "Fietsen door het groen"]]'::jsonb,false) on conflict (id) do nothing;
insert into bases (id,nr,name,dates,nights,lat,lon,hotel,alternative,why,todo,unsplash_query,maps_query,photo,photo_caption,gallery,links) values ('pkk',2,'Prachuap Khiri Khan','5–7 feb','2 nachten',11.745,99.79,'Andrographis Paniculata Resort','Tolani Resort Kui Buri (luxer, villa''s met plonsbad)','Eenvoudig maar mooi aan zee, met tuin en dakterras. Rustig, weinig westerse toeristen.',array['Maeklong-spoorwegmarkt onderweg','Phraya Nakhon-grot in Sam Roi Yot','Safari met wilde olifanten in Kui Buri','Strand van Ao Manao en de apenberg']::text[],'phraya-nakhon-cave','Andrographis Paniculata Resort Prachuap','06-prachuap','Vissersboot voor de eilanden bij Prachuap','[["04-maeklong", "Maeklong-spoorwegmarkt"], ["05-sam-roi-yot-grot", "Grot in Sam Roi Yot"], ["07-kui-buri-olifant", "Olifant, Kui Buri"]]'::jsonb,false) on conflict (id) do nothing;
insert into bases (id,nr,name,dates,nights,lat,lon,hotel,alternative,why,todo,unsplash_query,maps_query,photo,photo_caption,gallery,links) values ('chp',3,'Chumphon','7–9 feb','2 nachten',10.5651,99.2729,'Moonrise Villa','Nana Beach Resort (direct aan het strand, groter)','Familiehotel met ruime familiekamers, 100 meter van het strand van Thung Wua Laen. De eigenaren regelen ook snorkeltrips.',array['Stranddag aan Thung Wua Laen','Snorkeltrip naar de eilanden van Mu Ko Chumphon','Zonsopkomst op het strand','Visrestaurants aan de boulevard']::text[],'chumphon','Moonrise Villa Chumphon','17-chumphon-kust','De kust bij Chumphon bij eb','[["18-tempel-ban-krut", "Tempel bij Ban Krut, onderweg"], ["16-zonsondergang-golf", "Zonsondergang aan de Golf van Thailand"]]'::jsonb,false) on conflict (id) do nothing;
insert into bases (id,nr,name,dates,nights,lat,lon,hotel,alternative,why,todo,unsplash_query,maps_query,photo,photo_caption,gallery,links) values ('ks',4,'Khao Sok','9–11 feb','2 nachten',8.89,98.53,'Hotel Khao Sok & Spa','Our Jungle Camp (boomhutten, meertour geregeld)','Bungalows in een jungletuin met zwembad, aan de rand van het nationale park. De eigenaar spreekt zelfs een beetje Nederlands.',array['Tuben over de Sok-rivier','Nachtsafari in de jungle','Junglewandeling naar een waterval','Gibbons en neushoornvogels spotten']::text[],'khao-sok','Hotel Khao Sok & Spa','19-khao-sok-jungle','Jungle en kalkrotsen rond Khao Sok','[["20-junglepad", "Junglepad in het nationale park"]]'::jsonb,false) on conflict (id) do nothing;
insert into bases (id,nr,name,dates,nights,lat,lon,hotel,alternative,why,todo,unsplash_query,maps_query,photo,photo_caption,gallery,links) values ('kr',5,'Krabi (Tubkaek)','11–13 feb','2 nachten',8.09,98.75,'The Tubkaak Krabi Boutique Resort','Dusit Thani Krabi (groter, meer zwembaden)','Rustige baai met uitzicht op de eilanden, ver van de drukte van Ao Nang. Dragon Crest begint vlakbij.',array['Wandeling naar Dragon Crest (vóór 7 uur)','Klimcursus of deep water soloing op Railay']::text[],'railay-beach','The Tubkaak Krabi Boutique Resort','10-railay','Railay Beach met longtailboten','[["11-railay-kliffen", "Kliffen van Railay van bovenaf"]]'::jsonb,false) on conflict (id) do nothing;
insert into bases (id,nr,name,dates,nights,lat,lon,hotel,alternative,why,todo,unsplash_query,maps_query,photo,photo_caption,gallery,links) values ('kl',6,'Khao Lak','13–17 feb','4 nachten',8.65,98.25,'The Sands Khao Lak','The Little Shore (luxer zusterhotel)','Lazy river, glijbanen en een breed strand. Ideaal voor de laatste dagen.',array['Phang Nga Bay: Koh Panyee, kajakken, Samet Nangshe','Dagtrip naar de Surin-eilanden','Similan-eilanden of de waterval in Lam Ru','Laatste stranddag']::text[],'khao-lak','The Sands Khao Lak by Katathani','14-khao-lak-strand','Het brede strand van Khao Lak','[["12-phang-nga-mangrove", "Mangroves in Phang Nga"], ["13-samet-nangshe", "Uitzicht over Phang Nga Bay"], ["15-surin", "Baai op de Surin-eilanden"]]'::jsonb,true) on conflict (id) do nothing;

insert into days (day_date,title,drive,items,photo) values ('2027-02-03','Bangkok',null,array['Landing 06:35, direct inchecken en slapen','Wat Pho en de expressboot over de Chao Phraya','Avond: Jodd Fairs-nachtmarkt']::text[],'01-wat-arun') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-04','Bangkok',null,array['Fietstour door Bang Krachao','Middag vrij: Grand Palace of zwembad','Avond: Muay Thai in Rajadamnern en een rooftopbar']::text[],'03-bangkok-fietsen') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-05','Naar Prachuap Khiri Khan','4,5 u',array['Huurauto ophalen','Maeklong-spoorwegmarkt (check de treintijden)','Aankomst aan zee, Ao Manao']::text[],'04-maeklong') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-06','Sam Roi Yot en Kui Buri','2,5 u',array['Chinees Nieuwjaar','Ochtend: Phraya Nakhon-grot, licht rond 10–11 uur','Laat in de middag: safari met wilde olifanten in Kui Buri, op de terugweg']::text[],'05-sam-roi-yot-grot') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-07','Naar Chumphon','3 u',array['Ochtend: strand van Ao Manao en de apenberg','Onderweg: de tempel Wat Thang Sai bij Ban Krut','Avond: zonsondergang en vis aan het strand van Thung Wua Laen']::text[],'18-tempel-ban-krut') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-08','Chumphon',null,array['Snorkeltrip naar de eilanden van Mu Ko Chumphon','Middag: stranddag aan Thung Wua Laen']::text[],'17-chumphon-kust') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-09','Naar Khao Sok','3 u',array['Rit door het binnenland naar Khao Sok','Middag: tuben over de Sok-rivier','Avond: nachtsafari in de jungle']::text[],'19-khao-sok-jungle') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-10','Khao Sok',null,array['Junglewandeling in het nationale park naar een waterval','Middag: zwemmen in de rivier of het zwembad van het hotel']::text[],'20-junglepad') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-11','Naar Krabi','2,5 u',array['Rustig ontbijt in de jungle','Rit naar Tubkaek','Avond: zonsondergang aan het strand']::text[],null) on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-12','Krabi',null,array['Dragon Crest, vertrek vóór 7 uur','Longtailboot naar Railay: klimmen of deep water soloing']::text[],'11-railay-kliffen') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-13','Via Phang Nga naar Khao Lak','3 u',array['Koh Panyee en kajakken door de grotten','Uitzicht op Samet Nangshe','Inchecken in The Sands']::text[],'13-samet-nangshe') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-14','Surin-eilanden',null,array['Dagtrip met speedboot, ophalen bij het hotel','Snorkelen en het dorp van de Moken']::text[],'15-surin') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-15','Khao Lak',null,array['Similan-eilanden, of rustdag','Waterval in Lam Ru National Park']::text[],null) on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-16','Khao Lak',null,array['Laatste stranddag','Koffers pakken, auto-inlevering regelen']::text[],'14-khao-lak-strand') on conflict (day_date) do nothing;
insert into days (day_date,title,drive,items,photo) values ('2027-02-17','Naar huis','1,5 u',array['05:00 vertrek naar Phuket Airport','Auto inleveren, vlucht EY429 om 08:45']::text[],null) on conflict (day_date) do nothing;

insert into legs (sort,date_label,route,duration) values (1,'5 feb','Bangkok → Maeklong → Prachuap','4,5 u') on conflict (sort) do nothing;
insert into legs (sort,date_label,route,duration) values (2,'7 feb','Prachuap → Chumphon','3 u') on conflict (sort) do nothing;
insert into legs (sort,date_label,route,duration) values (3,'9 feb','Chumphon → Khao Sok','3 u') on conflict (sort) do nothing;
insert into legs (sort,date_label,route,duration) values (4,'11 feb','Khao Sok → Krabi (Tubkaek)','2,5 u') on conflict (sort) do nothing;
insert into legs (sort,date_label,route,duration) values (5,'13 feb','Krabi → Phang Nga Bay → Khao Lak','3 u') on conflict (sort) do nothing;
insert into legs (sort,date_label,route,duration) values (6,'17 feb','Khao Lak → Phuket Airport','1,5 u') on conflict (sort) do nothing;

insert into checklist (id,sort,title,note) values ('idp',1,'Internationaal rijbewijs aanvragen','ANWB, voor beide bestuurders') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('car',2,'Huurauto Bangkok → Phuket Airport','Ophalen 5 feb, inleveren 16 feb avond of 17 feb vroeg') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('h1',3,'ARUN Riverside, Bangkok','Vanaf 2 feb boeken, dan kun je direct inchecken') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('h2',4,'Prachuap Khiri Khan, 5–7 feb','Als eerste boeken: Chinees Nieuwjaar') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('chp',5,'Moonrise Villa, Chumphon, 7–9 feb','Vraag meteen naar de snorkeltrip') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('h3',6,'Hotel Khao Sok & Spa, 9–11 feb',null) on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('h4',7,'The Tubkaak, Krabi, 11–13 feb',null) on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('h5',8,'The Sands Khao Lak, 13–17 feb',null) on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('surin',9,'Dagtrip Surin-eilanden, 14 feb','Check of de eilanden open zijn') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('kui',10,'Olifantensafari Kui Buri, 6 feb',null) on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('snork',11,'Snorkeltrip Mu Ko Chumphon, 8 feb','Via het hotel') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('climb',12,'Klimcursus Railay, 12 feb',null) on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('muay',13,'Tickets Muay Thai, 4 feb','Rajadamnern-stadion') on conflict (id) do nothing;
insert into checklist (id,sort,title,note) values ('ins',14,'Reisverzekering controleren','Inclusief snorkelen en klimmen') on conflict (id) do nothing;

commit;
